# Usage:
# askbend -c askbend.toml

# Question answering config
[qa]
path = "data/"
database = "askbend"
table = "doc"
# Data source name (DSN) for connecting to your Databend cloud warehouse
# https://docs.databend.com/using-databend-cloud/warehouses/connecting-a-warehouse
dsn = "databend://<sql-user>:<sql-password>@<your-databend-cloud-warehouse>/default"
top = 3

[github]
github_token = ""
llm_max_tokens = 100000
dsn = "databend://<sql-user>:<sql-password>@<your-databend-cloud-warehouse>/default"
repos = [""]
