[package]
name = "askbend"
version = "0.1.0"
edition = "2021"

[lib]
doctest = false
test = false

[[bin]]
name = "askbend"
path = "bin/ask.rs"
doctest = false
test = false

[dependencies]
clap = { version = "4.1.7", features = ["derive", "env"] }
chrono = "0.4.24"
comrak = "0.18.0"
databend-driver = "0.1.4"
log = "0.4.0"
env_logger = "0.9.0"
regex = "1.7.3"
serde = { version = "1.0.159", features = ["derive"] }
serfig = "0.0.3"
actix-web = "4.3.1"
anyhow = "1.0.58"
syn = "1.0"
proc-macro2 = "1.0"
quote = "1.0"
markdown = "0.3.0"
tokio = { version = "1.19.2", features = ["full"] }
tokio-stream = "0.1.12"
walkdir = "2.3.3"

[dev-dependencies]
